services:
  # A Docker web service
  - type: web
    name: Autofilter-render
    env: python
    startCommand: python3 bot.py
    buildCommand: pip install -r requirements.txt
    repo: https://github.com/Jot4349/Autofilter-render.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: v10.0__Revised_]_super_prime # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
